language: node_js

node_js:
  - "6.5.0"

before_install:
  - npm install karma --save-dev
  - npm install karma-jasmine karma-chrome-launcher jasmine-core --save-dev
  - npm install -g karma-cli
  - npm install --save-dev karma-phantomjs-launcher
  - npm install --save-dev jasmine

before_script:
  - npm install -g gulp
script: gulp karma-test